# Generated by Django 2.0 on 2018-04-02 00:31

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accountId', models.CharField(max_length=200)),
                ('clientId', models.CharField(max_length=200)),
                ('clientSecret', models.CharField(max_length=200)),
                ('liveAccountId', models.CharField(max_length=200)),
                ('liveApiToken', models.CharField(max_length=200)),
                ('liveClippingCreds', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('content_dir', models.CharField(max_length=200)),
                ('smil_file', models.CharField(max_length=200)),
                ('ProgramBlockList', django_mysql.models.ListTextField(models.IntegerField(), size=20)),
                ('bcAccount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simlive.BCAccount')),
            ],
        ),
    ]
